# Generated by Django 6.0.6 on 2026-06-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_city_options_alter_city_name_alter_city_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='location',
            name='verified',
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
    ]
