# Generated by Django 6.0.6 on 2026-06-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_location_added_by_remove_location_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
    ]
