# Generated by Django 6.0.6 on 2026-06-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_country_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
    ]
