# Generated by Django 6.0.6 on 2026-06-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_remove_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, help_text='City name in English', max_length=50),
        ),
    ]
