# Generated by Django 6.0.6 on 2026-06-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_city_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='is_capital',
            field=models.BooleanField(default=False, help_text='Is this the capital city?'),
        ),
    ]
