# Generated by Django 6.0.6 on 2026-06-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_alter_city_options_city_is_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='location_type',
            field=models.CharField(blank=True, help_text='Optional special location type, e.g. Island, National Park', max_length=50),
        ),
    ]
