# Generated by Django 6.0.6 on 2026-06-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_city_location_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(help_text='Country name in English', max_length=100)),
                ('city_name', models.CharField(help_text='City name in English', max_length=100)),
                ('location_name', models.CharField(help_text='Name of the shop or place', max_length=200)),
                ('google_maps_url', models.URLField(help_text='Link to Google Maps')),
                ('description', models.TextField(blank=True, help_text='Description of the place and what pins are available')),
                ('photo_url', models.URLField(blank=True, help_text='Link to a photo of the pins (optional)')),
                ('has_city_pins', models.BooleanField(default=False)),
                ('has_country_pins', models.BooleanField(default=False)),
                ('has_place_pins', models.BooleanField(default=False)),
                ('submitter_email', models.EmailField(blank=True, help_text='Your email (optional)', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for review')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
