# Generated by Django 6.0.6 on 2026-06-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_locationsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsubmission',
            name='google_maps_url',
            field=models.URLField(help_text='Link to Google Maps', max_length=500),
        ),
    ]
