# Generated by Django 6.0.6 on 2026-06-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_alter_locationsubmission_google_maps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsubmission',
            name='country_name',
            field=models.CharField(help_text='Country name in English', max_length=30),
        ),
        migrations.AlterField(
            model_name='locationsubmission',
            name='description',
            field=models.TextField(help_text='Description of the place and what pins are available'),
        ),
        migrations.AlterField(
            model_name='locationsubmission',
            name='location_name',
            field=models.CharField(help_text='Name of the shop or place', max_length=100),
        ),
        migrations.AlterField(
            model_name='locationsubmission',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Link to a photo of the pins (optional)', max_length=500),
        ),
        migrations.AlterField(
            model_name='locationsubmission',
            name='submitter_email',
            field=models.EmailField(blank=True, help_text='Your email (optional)', max_length=100),
        ),
    ]
