# Generated by Django 6.0.6 on 2026-07-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_alter_locationsubmission_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='yandex_maps_url',
            field=models.URLField(blank=True, help_text='Used instead of Google Maps for locations in Russia, where Google Maps works poorly'),
        ),
    ]
