# Generated by Django 6.0.6 on 2026-07-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_location_yandex_maps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsubmission',
            name='status',
            field=models.CharField(choices=[('pending', '🟡 Pending'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected')], default='pending', max_length=20),
        ),
    ]
