# Generated by Django 6.0.6 on 2026-07-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_alter_locationsubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at (UTC)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at (UTC)'),
        ),
        migrations.AlterField(
            model_name='locationsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at (UTC)'),
        ),
    ]
