# Generated by Django 6.0.6 on 2026-07-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_alter_location_created_at_alter_location_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsubmission',
            name='contributor_nickname',
            field=models.CharField(blank=True, help_text='Nickname to credit you in the Contributors list on the site (optional)', max_length=50),
        ),
    ]
