# Generated by Django 6.0.6 on 2026-07-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0015_locationsubmission_contributor_nickname'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='country',
            name='has_states',
            field=models.BooleanField(default=False, help_text='Show a state/region layer for this country (e.g. USA): Country → State → City instead of Country → City'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='State/region name in English', max_length=50)),
                ('slug', models.SlugField(blank=True, help_text='Generated automatically from the name')),
                ('code', models.CharField(blank=True, help_text='Optional abbreviation, e.g. CA, NY', max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='locations.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Only for countries with Country.has_states=True (e.g. USA). Leave blank otherwise.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.state'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('state__isnull', True)), fields=('country', 'slug'), name='unique_city_slug_per_country_without_state'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('state__isnull', False)), fields=('state', 'slug'), name='unique_city_slug_per_state'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('country', 'slug')},
        ),
    ]
