# Generated by Django 6.0.6 on 2026-08-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0016_alter_city_unique_together_country_has_states_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='contributor_nickname',
            field=models.CharField(blank=True, help_text="Shown in the community badge on the site, e.g. 'Added by Anna'. Leave blank to show an unnamed 'Community-added' badge.", max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='source',
            field=models.CharField(choices=[('owner', 'Site owner'), ('community', 'Community')], default='owner', help_text='Site owner: no badge shown on the site. Community: shows a contribution badge on the location card.', max_length=20),
        ),
    ]
