# Generated by Django 6.0.6 on 2026-08-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0017_location_contributor_nickname_location_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='youtube_walk_url',
            field=models.URLField(blank=True, help_text='Optional Vagabondity walking tour for this city or place', max_length=500),
        ),
    ]
