# Generated by Django 6.0.6 on 2026-08-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0018_city_youtube_walk_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='note',
            field=models.TextField(blank=True, help_text="Optional public note shown above this city's locations"),
        ),
    ]
