# Generated by Django 6.0.6 on 2026-08-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_city_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='custom_flag',
            field=models.CharField(blank=True, help_text='Optional custom flag image path inside static/, e.g. flags/south_ossetia.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, help_text='Optional ISO country code, used to display a flag', max_length=2, null=True, unique=True),
        ),
    ]
