# Generated by Django 6.0.6 on 2026-08-28

from django.db import migrations, models


def enable_direct_city_pages(apps, schema_editor):
    Country = apps.get_model("locations", "Country")
    City = apps.get_model("locations", "City")

    for name in ["San Marino", "Singapore", "Hong Kong", "Macau"]:
        country = Country.objects.filter(name=name).first()
        if country and City.objects.filter(
            country=country,
            name=name,
            state__isnull=True,
        ).exists():
            country.opens_city_directly = True
            country.save(update_fields=["opens_city_directly"])


def disable_direct_city_pages(apps, schema_editor):
    Country = apps.get_model("locations", "Country")
    Country.objects.filter(name__in=["San Marino", "Singapore", "Hong Kong", "Macau"]).update(
        opens_city_directly=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0020_country_custom_flag_alter_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="opens_city_directly",
            field=models.BooleanField(
                default=False,
                help_text="Open the identically named city at this country's URL, for places such as Singapore.",
            ),
        ),
        migrations.RunPython(enable_direct_city_pages, disable_direct_city_pages),
    ]
