# Generated by Django 6.0.6 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0021_country_opens_city_directly"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="mobile_name",
            field=models.CharField(
                blank=True,
                help_text="Optional shorter country name shown on mobile homepage cards",
                max_length=30,
            ),
        ),
    ]
