# Generated by Django 6.0.8 on 2026-09-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0022_country_mobile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_pincredible',
            field=models.BooleanField(default=False, verbose_name='Pincredible'),
        ),
        migrations.AlterField(
            model_name='location',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
